id: P001655
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG8317
  title: ཕུགས་ནོར་དང་པོའི་གཟི་དཔལ།
  author: ''
  volumes:
    eabdfcb6dd3a480daef42bc7daac1c4d:
      image_group_id: I1KG8497
      title: ''
      volume_number: 1
      total_pages: 182
      base_file: v001.txt
